import { Prodotto } from "./Prodotto";


export const fakeObject : Prodotto[] = [
    new Prodotto("panino","Big Bro","../../assets/prodotti/panini/big-bro_isolated.png",5.69),
    new Prodotto("panino","Loco Burger","../../assets/prodotti//panini/burger-isolated.png",5.50),
    new Prodotto("panino","Loco Cheese Burger","../../assets/prodotti/panini/cheese-isolated.png",3.6),
    new Prodotto("panino","Chicken Kebab","../../assets/prodotti/panini/chicken-kebab-isolated.png",3.6),
    new Prodotto("panino","Double Cheese Burger","../../assets/prodotti/panini/double-cheese-isolated.png",3.6),
    new Prodotto("panino","Founders Selection Asiago","../../assets/prodotti/panini/founders-selection-asiago-isolated.png",3.6),
    new Prodotto("panino","Founders Selection BBQ","../../assets/prodotti/panini/founders-selection-bbq-isolated.png",3.6),
    new Prodotto("panino","Founders Selection Chicken","../../assets/prodotti/panini/founders-selection-chicken-isolated.png",3.6),
    new Prodotto("panino","Big Chicken & Bacon","../../assets/prodotti/panini/gran-chicken-bacon-isolated.png",3.6),
    new Prodotto("panino","Only Big Pig","../../assets/prodotti/panini/gran-pig-isolated.png",3.6),
    new Prodotto("panino","Original Chicken","../../assets/prodotti/panini/original-chicken-isolated.png",3.6),
    new Prodotto("panino","Only Big Pig Kebab","../../assets/prodotti/panini/pig-kebab-isolated.png",3.6),
    new Prodotto("bibita","Acqua","../../assets/prodotti/bibite/acqua-lilla_isolated.png",3.6),
    new Prodotto("bibita","Birra","../../assets/prodotti/bibite/birra_isolated.png",3.6),
    new Prodotto("bibita","CaffÃ¨","../../assets/prodotti/bibite/caffe-isolated.png",3.6),
    new Prodotto("bibita","Coca Cola Zero","../../assets/prodotti/bibite/cocacola_zero-logo-isolated.png",3.6),
    new Prodotto("bibita","Coca Cola","../../assets/prodotti/bibite/cocacola-logo-isolated.png",3.6),
    new Prodotto("bibita","Fanta","../../assets/prodotti/bibite/fanta-logo-isolated.png",3.6),
    new Prodotto("bibita","Lipton Lemon","../../assets/prodotti/bibite/logo-lipton-lemon-isolated.png",3.6),
    new Prodotto("bibita","Lipton Peach","../../assets/prodotti/bibite/logo-lipton-peach-isolated.png",3.6),
    new Prodotto("bibita","Sprite","../../assets/prodotti/bibite/sprite-logo-isolated.png",3.6),
    new Prodotto("bibita","Succo Mela","../../assets/prodotti/bibite/succo-mela_isolated.png",3.6),
    new Prodotto("bibita","Tropicana","../../assets/prodotti/bibite/tropicana-isolated.png",3.6),
    new Prodotto("insalata","Insalata Mista","../../assets/prodotti/insalate/insalata-mista-isolated.png",3.6),
    new Prodotto("insalata","Insalata Pollo Croccante","../../assets/prodotti/insalate/insalata-pollo-croccante-isolated.png",3.6),
    new Prodotto("insalata","Insalata Pollo Grigliato","../../assets/prodotti/insalate/insalata-pollo-grigliato-isolated.png",3.6),
    new Prodotto("insalata","Insalata Verde con Pomodori","../../assets/prodotti/insalate/insalata-verde-pomodori-isolated.png",3.6),
    new Prodotto("salsa","Salsa Ketchup","../../assets/prodotti/salse/ketchup_isolated.png",3.6),
    new Prodotto("salsa","Salsa Maionese","../../assets/prodotti/salse/maionese_isolated.png",3.6),
    new Prodotto("salsa","Salsa Agrodolce","../../assets/prodotti/salse/salsa-agrodolce_isolated.png",3.6),
    new Prodotto("salsa","Salsa BBQ","../../assets/prodotti/salse/salsa-barbecue_isolated.png",3.6),
    new Prodotto("salsa","Salsa Senape","../../assets/prodotti/salse/senape_isolated.png",3.6),
    new Prodotto("sfiziosita","MDJ Chicken Nuggets","../../assets/prodotti/sfiziosita/pepite-asiago-speck-isolated.png",3.6),
    new Prodotto("sfiziosita","Chicken Wings","../../assets/prodotti/sfiziosita/chicken-wings-isolated.png",3.6),
    new Prodotto("sfiziosita","Pepite Asiago & Speck","../../assets/prodotti/sfiziosita/chicken-MDJnuggets-isolated.png",3.6),
];